import _IMG_REINO_EQUINO from './reino-equino.webp';
import _IMG_TARJETA from './tarjeta.webp';
import _IMG_USER from './user.png';
import _IMG_TRIANGULO from './triangulo.png';
import _IMG_BENEFICIO1 from  './beneficios/Beneficio1.png';
import _IMG_BENEFICIO2 from  './beneficios/Beneficio2.png';
import _IMG_BENEFICIO3 from  './beneficios/Beneficio3.png';
import _IMG_BENEFICIO4 from  './beneficios/Beneficio4.png';
import _IMG_BENEFICIO5 from  './beneficios/Beneficio5.png';
import _IMG_BENEFICIO6 from  './beneficios/Beneficio6.png';
import _IMG_BENEFICIO7 from  './beneficios/Beneficio7.png';
import _IMG_BENEFICIO8 from  './beneficios/Beneficio8.png';
import _IMG_BENEFICIO9 from  './beneficios/Beneficio9.png';

export const IMG_REINO_EQUINO = _IMG_REINO_EQUINO;
export const IMG_TARJETA = _IMG_TARJETA;
export const IMG_USER = _IMG_USER;
export const IMG_BENEFICIO1= _IMG_BENEFICIO1;
export const IMG_BENEFICIO2= _IMG_BENEFICIO2;
export const IMG_BENEFICIO3= _IMG_BENEFICIO3;
export const IMG_BENEFICIO4= _IMG_BENEFICIO4;
export const IMG_BENEFICIO5= _IMG_BENEFICIO5;
export const IMG_BENEFICIO6= _IMG_BENEFICIO6;
export const IMG_BENEFICIO7= _IMG_BENEFICIO7;
export const IMG_BENEFICIO8= _IMG_BENEFICIO8;
export const IMG_BENEFICIO9= _IMG_BENEFICIO9;
export const IMG_TRIANGULO= _IMG_TRIANGULO;